-- STUDENT_REST TABLE
CREATE TABLE STUDENT_REST
(
	STUDENT_REST_ID VARCHAR2(4000),
	STUDENT_NAME VARCHAR2(4000),
	STUDENT_ROLL_NO VARCHAR2(4000),
	PRIMARY KEY(STUDENT_ID)
);

--STUDENT_ADDRESS_REST TABLE

CREATE TABLE STUDENT_ADDRESS_REST
(
	STUDENT_ADDRESS_ID VARCHAR2(4000),
	STREET VARCHAR2(4000),
	CITY VARCHAR2(40),
	STATE VARCHAR2(40),
	PINCODE VARCHAR2(10),
	STUDENT_REST_ID_FK VARCHAR2(4000),
	PRIMARY KEY(STUDENT_ADDRESS_ID),
	FOREIGN KEY (STUDENT_REST_ID_FK) REFERENCES STUDENT_REST(STUDENT_REST_ID)
);